#!/usr/bin/env python3
"""Generate a standard WealthOS domain module skeleton.

Usage (from backend/):

    uv run python scripts/create_module.py accounts
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES_ROOT = ROOT / "src" / "wealthos" / "modules"

DIRECTORIES = [
    "api",
    "application/commands",
    "application/queries",
    "application/services",
    "domain/entities",
    "domain/repositories",
    "domain/value_objects",
    "infrastructure/models",
    "infrastructure/repositories",
    "infrastructure/mappers",
    "schemas",
    "tests",
]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def create_module(name: str) -> Path:
    if not name.isidentifier() or name != name.lower():
        raise SystemExit("Module name must be a lowercase Python identifier (e.g. organizations).")

    root = MODULES_ROOT / name
    if root.exists():
        raise SystemExit(f"Module already exists: {root}")

    for relative in DIRECTORIES:
        directory = root / relative
        directory.mkdir(parents=True, exist_ok=True)
        _write(directory / "__init__.py", '"""Package."""\n')

    title = name.replace("_", " ").title()

    _write(
        root / "README.md",
        f"""# {title}

## Purpose

Describe why this module exists.

## Responsibilities

- TBD

## Public API

- `GET /{name}`
- `POST /{name}`

## Notes

Generated by `scripts/create_module.py`.
Register in `wealthos.modules.MODULES` to expose HTTP routes.
""",
    )

    _write(
        root / "domain" / "exceptions.py",
        f'''"""Domain errors for the {name} module."""


class {title.replace(" ", "")}Error(Exception):
    """Base domain error."""


class {title.replace(" ", "")}NotFoundError({title.replace(" ", "")}Error):
    """Raised when the aggregate cannot be found."""
''',
    )

    _write(
        root / "api" / "dependencies.py",
        '''"""FastAPI dependencies for this module."""
''',
    )

    _write(
        root / "api" / "router.py",
        f'''"""HTTP routes for the {name} module."""

from fastapi import APIRouter

router = APIRouter()


@router.get("/health", include_in_schema=False)
async def {name}_module_health() -> dict[str, str]:
    """Lightweight probe used while the module is scaffolding."""
    return {{"module": "{name}", "status": "ready"}}
''',
    )

    _write(root / "__init__.py", f'"""{title} module."""\n')

    return root


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: uv run python scripts/create_module.py <module>")
    path = create_module(sys.argv[1])
    print(f"Module created at {path}")
    print("Next: add the name to wealthos.modules.MODULES")


if __name__ == "__main__":
    main()
